version: '3'

volumes:
  pgdata:

services:
  api:
    build: .
    command: /app/bin/entrypoint.sh --wait --migrate --dev
    container_name: api
    environment:
      - ENV=dev
      - POSTGRES_SERVICE_HOST=db
      - POSTGRES_SERVICE_PORT=5432
      - SECRET_KEY=super_safe_secret
    volumes:
      - .:/app
      - ./static:/static
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432
    ports:
      - 5432:5432
