# Generated by Django 3.2.4 on 2021-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_node", models.CharField(max_length=10)),
                ("end_node", models.CharField(max_length=10)),
            ],
        ),
    ]
